name: task 3

on: push

jobs:
  run_cypress_tests:
    runs-on: ubuntu-latest
    container: 
      image: c
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/isolation/*
      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: firefox
          spec: cypress/e2e/isolation/*
      - name: "UI Tests - Edge"
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: edge
          spec: cypress/e2e/isolation/*      