name: task 3

on: push

jobs:
  run_cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run tests
        run: 
          npm install
          npm start
          npx cypress run --spec "cypress/e2e/isolation/*" --browser chrome --headed
