name: task 3

on:
  push:
    branches:
      - bury08

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run install
        run:
          npm install